Description:
  test-blog

Resources:
    TestVPC:                   
      Type: AWS::EC2::VPC             
      Properties:
        CidrBlock: 10.1.0.0/16      
        Tags:            
          - Key: Name
            Value: TEST-VPC

  